#! /usr/bin/env python

'''
Run Focus Blur filter non-interactively.
'''

import sys
import os
import subprocess
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import tempfile
import re

REDIM = re.compile(r'(\d{2,})x\d{2,}')

SCRIPT = '''
(let*
    (
        (img (car (gimp-file-load RUN-NONINTERACTIVE "%s" "%s")))
        (map (car (gimp-file-load RUN-NONINTERACTIVE "%s" "%s")))
        (imgdwb (car (gimp-image-get-active-layer img)))
        (mapdwb (car (gimp-image-get-active-layer map)))
    )
    (plug-in-focusblur RUN-NONINTERACTIVE img imgdwb %s %s %s mapdwb %s %s %s)
    (gimp-file-save RUN-NONINTERACTIVE img imgdwb "%s" "%s")
)
'''

MODELS = ('Flat', 'Spherical', 'Gaussian', 'Ring', 'Concave', 'Brush')

def main():
    '''
    Run Inkscape and Focus Blur plug-in with GIMP
    '''

    # Parse arguments
    parser = ArgumentParser(description=__doc__,
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('inimage', help="input image")
    parser.add_argument('--model', choices=MODELS, default='Flat',
                        help="model of blurring")
    parser.add_argument('radius', help="radius for blurring")
    parser.add_argument('--depth', default=0, help="focal depth")
    parser.add_argument('insvg', help="depth map file")
    parser.add_argument('shining', help="radius for shining")
    parser.add_argument('--threshold', default=2, help="threshold for shining")
    parser.add_argument('--noprecedence', action='store_false',
                        help="depth precedence")
    parser.add_argument('outimage', help="output image")
    parser.add_argument('--debug', action='store_false')
    args = parser.parse_args()

    # Get input file dimensions
    proc = subprocess.Popen(['file', args.inimage], stdout=subprocess.PIPE)
    out, _ = proc.communicate()
    width = REDIM.search(out).group(1)

    # Open /dev/null if needs be
    devnull = open(os.devnull, 'w') if args.debug else None

    # Export Inkscape depth map
    tmp = tempfile.NamedTemporaryFile()
    subprocess.call(['inkscape', '-e', tmp.name, '-w', width, args.insvg],
                    stdout=devnull)

    # Run plug-in
    subprocess.call(['gimp', '-i',
                     '-b', SCRIPT % (args.inimage, args.inimage,
                                     tmp.name, tmp.name,
                                     MODELS.index(args.model),
                                     args.radius,
                                     args.depth,
                                     args.shining,
                                     args.threshold,
                                     1 if args.noprecedence else 0,
                                     args.outimage, args.outimage),
                     '-b', '(gimp-quit 0)'],
                    stderr=devnull)


if __name__ == '__main__':
    sys.exit(main())
